- name: Init cluster
  shell: "kubeadm init --pod-network-cidr=172.16.0.0/16 2>&1 | tee /home/{{ ansible_ssh_user }}/k8s-init.log"
  args:
    creates: '/home/{{ ansible_ssh_user }}/k8s-init.log'

- name: Create config dir
  file:
    path: '/home/{{ ansible_ssh_user }}/.kube'
    state: directory
    owner: '{{ ansible_ssh_user }}'
    group: '{{ ansible_ssh_user }}'

- name: Copy config file
  copy:
    remote_src: true
    src: /etc/kubernetes/admin.conf
    dest: '/home/{{ ansible_ssh_user }}/.kube/config'
    owner: '{{ ansible_ssh_user }}'
    group: '{{ ansible_ssh_user }}'

- name: Download calico manifest
  get_url:
    url: https://docs.projectcalico.org/v3.10/manifests/calico.yaml
    dest: '/home/{{ ansible_ssh_user }}/calico.yaml'

- name: Change POD CIDR
  replace:
    path: '/home/{{ ansible_ssh_user }}/calico.yaml'
    regexp: "192.168.0.0\/16"
    replace: "172.16.0.0/16"

- name: Apply calico manifest
  shell: |
    kubectl apply -f calico.yaml
    touch calico.yaml.applied
  args:
    creates: '/home/{{ ansible_ssh_user }}/calico.yaml.applied'
  become: false

- name: Untaint master
  shell: |
    kubectl taint nodes --all node-role.kubernetes.io/master-
  become: false
  ignore_errors: true # TODO :\
