- name: Init cluster
  shell: "kubeadm init --pod-network-cidr=172.16.0.0/16 | tee /home/deploy/k8s-init.log"
  args:
    creates: /home/deploy/k8s-init.log

- name: Create config dir
  file:
    path: /home/deploy/.kube
    state: directory
    owner: deploy
    group: deploy

- name: Copy config file
  copy:
    remote_src: true
    src: /etc/kubernetes/admin.conf
    dest: /home/deploy/.kube/config
    owner: deploy
    group: deploy

- name: Download calico manifest
  get_url:
    url: https://docs.projectcalico.org/v3.10/manifests/calico.yaml
    dest: /home/deploy/calico.yaml

- name: Change POD CIDR
  replace:
    path: /home/deploy/calico.yaml
    regexp: "192.168.0.0\/16"
    replace: "172.16.0.0/16"

- name: Apply calico manifest
  shell: |
    kubectl apply -f calico.yaml
    touch calico.yaml.applied
  args:
    creates: /home/deploy/calico.yaml.applied
  become: false

- name: Untaint master
  shell: |
    kubectl taint nodes --all node-role.kubernetes.io/master-
  become: false
  ignore_errors: true # TODO :\
