- name: Install needed packages
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg2
      - software-properties-common

- name: Add docker GPG key
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: Add docker apt repository
  apt_repository:
    repo: deb https://download.docker.com/linux/debian buster stable
    state: present
    filename: docker

- name: Install docker-ce package
  apt:
    name:
      - docker-ce-cli=5:19.03.4~3-0~debian-buster
      - docker-ce=5:19.03.4~3-0~debian-buster
    state: present

- name: Enable and start docker service
  systemd:
    name: docker
    state: started
    enabled: yes

- name: Add deploy user to docker group
  user:
    name: deploy
    groups: docker
    append: yes
